//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesImHereData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.Images = new HashSet<Images>();
            this.Console = new HashSet<Console>();
        }
    
        public int GameId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfRelease { get; set; }
        public string Type { get; set; }
        public decimal Price { get; set; }
        public decimal GolbalNote { get; set; }
        public int OwnerId { get; set; }
        public bool IsSold { get; set; }
        public decimal Rating { get; set; }
        public int ConsoleId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Console> Console { get; set; }
    }
}
